language: node_js
addons:
  apt:
    packages:
      - libavahi-compat-libdnssd-dev
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10'
after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
